export const SAMPLE_TEXTS = [
  'The quick brown fox jumps over the lazy dog',
  'Pack my box with five dozen liquor jugs',
  'How razorback-jumping frogs can level six piqued gymnasts',
  'Cozy lummox gives smart squid',
  'Jaded zombies acted quaintly but kept driving their oxen forward',
  'The five boxing wizards jump quickly',
  'A quick brown fox jumps over the lazy dog',
  'The jay, pig, fox, zebra, and my wolves quack',
  'Sympathizing would fix Quaker objectives',
  'A wizard’s job is to vex chumps quickly in fog',
  'Watch “Jeopardy!”, Alex Trebek’s fun TV quiz game',
  'By Jove, my quick study of lexicography won a prize',
  'Amazingly few discotheques provide',
  'A very big box sailed up then whizzed quickly from Japan',
  'Jack quietly moved up front and seized the big ball of wax',
  'The quick onyx goblin jumps over the lazy dwarf',
  'Six big devils from Japan quickly forgot how to waltz',
  'Big July earthquakes confound zany experimental vow',
  'Foxy parsons quiz and cajole the lovably dim',
];
